Repository Noostak/Noostak_Android, pull requests merged in 2025-04, with the labels that each got.

#78 [Feature/#56] 약속 생성, 그룹 상세 API 연결
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  data/src/main/java/com/sopt/data/datasource/AppointmentCreateDataSource.kt
  data/src/main/java/com/sopt/data/datasource/GroupDetailDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/AppointmentCreateDataSourceImpl.kt
  data/src/main/java/com/sopt/data/datasourceimpl/GroupDetailDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/request/RequestPostAppointmentCreateDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupConfirmedDetailDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupConfirmedDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupMembersDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupOngoingDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupConfirmedDetailDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupConfirmedDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupDetailInfoDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupOngoingDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/AppointmentCreateRepositoryImpl.kt
  data/src/main/java/com/sopt/data/repositoryimpl/GroupDetailRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/ApiKeyStorage.kt
  data/src/main/java/com/sopt/data/service/AppointmentCreateApiService.kt
  data/src/main/java/com/sopt/data/service/GroupDetailApiService.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupConfirmedAppointmentsEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupDetailInfoEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  domain/src/main/java/com/sopt/domain/repository/AppointmentCreateRepository.kt
  domain/src/main/java/com/sopt/domain/repository/GroupDetailRepository.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ProgressScreen.kt
Labels: ⭐ [FEAT], :cloud: 하늘

#77 [Feature/#66] : 약속 관련 api 연결
  core/src/main/java/com/sopt/core/designsystem/component/chip/AvailableUserChips.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/UnavailableUserChips.kt
  data/src/main/java/com/sopt/data/datasource/AppointmentConfirmDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/AppointmentConfirmDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/request/RequestPostTimeTableDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupConfirmedDetailDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupOngoingDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetOptionDetailDto.kt
  data/src/main/java/com/sopt/data/dto/response/base/BaseFriendsDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetConfirmedDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetOptionsDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/AppointmentConfirmRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/ApiKeyStorage.kt
  data/src/main/java/com/sopt/data/service/AppointmentConfirmApiService.kt
  domain/src/main/java/com/sopt/domain/entity/AppointmentDetailEntity.kt
  domain/src/main/java/com/sopt/domain/repository/AppointmentConfirmRepository.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/navigation/AppointmentNavigation.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/CurrentStatusScreen.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/splash/SplashViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberRoute.kt
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#76 [Feature/#75] 마이페이지 내 정보 조회/수정 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImage.kt
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImagePicker.kt
  core/src/main/res/xml/file_paths.xml
  data/src/main/java/com/sopt/data/datasource/ProfileDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/ProfileDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetProfileDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetProfileDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/ProfileRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/ProfileApiService.kt
  domain/src/main/java/com/sopt/domain/entity/ProfileEntity.kt
  domain/src/main/java/com/sopt/domain/entity/UserEntity.kt
  domain/src/main/java/com/sopt/domain/repository/ProfileRepository.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarGroupItem.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupItem.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileState.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileViewModel.kt
Labels: ⭐ [FEAT], :four_leaf_clover: 언지

#81 [Feature/#80] : 캘린더 그룹 조회 api 연결
  domain/src/main/java/com/sopt/domain/entity/CalendarGroupEntity.kt
  domain/src/main/java/com/sopt/domain/usecase/GetCalendarGroupsUseCase.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarGroup.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarGroupItem.kt
Labels: ⭐ [FEAT], :fallen_leaf: 가을

#85 [Feature/#82] : 공백만 입력 방지
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateInfo/AppointmentCreateInfoRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateInfo/AppointmentCreateInfoViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreatePeriod/AppointmentCreatePeriodViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], :cloud: 하늘

#87 [Feature/#86] : UI 변경 및 약속 생성 백스택 정리
  core/src/main/java/com/sopt/core/designsystem/component/timetable/NoostakEditableTimeTable.kt
  domain/build.gradle.kts
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmitComplete/AppointmentSubmitCompleteRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/navigation/GroupDetailNavigation.kt
Labels: ✅ [MOD], :fallen_leaf: 가을
