Repository Noostak/Noostak_Android, pull requests merged in 2025-02, with the labels that each got.

#41 [Feature/#39] : 온보딩 UI & 로그인/프로필 수정
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/OtpInputField.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LogInRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/OnboardingRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/checkInvite/CheckInviteRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/checkInvite/navigation/CheckInviteNavigation.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/inputGroupCode/InputGroupCodeRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/inputGroupCode/navigation/InputGroupCodeNavigation.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/navigation/SignUpNavigation.kt
  presentation/src/main/java/com/sopt/presentation/group/navigation/GroupNavigation.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileViewModel.kt
  presentation/src/main/res/drawable/ic_invite_code.xml
  presentation/src/main/res/drawable/ic_onboarding_1.xml
  presentation/src/main/res/drawable/ic_onboarding_2.xml
  presentation/src/main/res/drawable/ic_onboarding_3.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], 💟 [UI], :rabbit: 유진

#46 [Feature/#44] : 캘린더 그룹 리스트 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/NoostakTopAppBar.kt
  core/src/main/java/com/sopt/core/designsystem/theme/Type.kt
  core/src/main/java/com/sopt/core/extension/LazyListStateExt.kt
  core/src/main/res/drawable/ic_logo.xml
  domain/src/main/java/com/sopt/domain/entity/CalendarGroupEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarFloatingActionDialog.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarGroup.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/CalendarGroupItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/navigation/CalendarNavigation.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupImage.kt
  presentation/src/main/res/drawable/ic_calendar_add.xml
  presentation/src/main/res/values/strings.xml
Labels: 💟 [UI], :fallen_leaf: 가을

#49 [Feature/#45] 약속 생성 리팩
  core/src/main/java/com/sopt/core/designsystem/component/calendar/NoostakCalendar.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/NoostakTimePicker.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/TimeDisplay.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/TimePicker.kt
  core/src/main/java/com/sopt/core/util/calendar/Calendar.kt
  core/src/main/java/com/sopt/core/util/timepicker/TimePicker.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreatePeriod/AppointmentCreatePeriodRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], :cloud: 하늘

#47 [Feature/#43] 캘린더 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarDay.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonth.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonthPager.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarScheduleGroup.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarWeek.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/NoostakCalendar.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/ScheduleItem.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/WeekDaysHeader.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/YearMonthHeader.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/TimeDisplay.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/TimePicker.kt
  core/src/main/java/com/sopt/core/extension/CalendarExt.kt
  core/src/main/java/com/sopt/core/extension/CategoryColorExt.kt
  core/src/main/java/com/sopt/core/extension/LocalDateExt.kt
  core/src/main/java/com/sopt/core/type/WeekDayType.kt
  core/src/main/java/com/sopt/core/util/calendar/Calendar.kt
  core/src/main/java/com/sopt/core/util/timepicker/TimePicker.kt
  domain/src/main/java/com/sopt/domain/entity/CalendarSchedule.kt
  domain/src/main/java/com/sopt/domain/entity/DayEntity.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarMonthScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
Labels: 💟 [UI], :rabbit: 유진

#52 [Feature/#48] 캘린더 팝업 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/bottomsheet/NoostakBottomSheet.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonth.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonthPager.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarWeek.kt
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/NoostakTopAppBar.kt
  core/src/main/java/com/sopt/core/designsystem/screen/NoostakEmptyScreen.kt
  core/src/main/res/drawable/ic_back_24.xml
  domain/build.gradle.kts
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarMonthScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleColorChip.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleDetailScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/res/drawable/ic_back_48.xml
  presentation/src/main/res/values/strings.xml
Labels: 💟 [UI], :four_leaf_clover: 언지
