Repository Noostak/Noostak_Android, pull requests merged in 2025-01, with the labels that each got.

#7 [Feature/#5] : 그룹 상세 페이지 구현
  core/src/main/java/com/sopt/core/designsystem/component/button/NoostakFloatingActionButton.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakCategoryChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakUserChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/NoostakTopAppBar.kt
  core/src/main/java/com/sopt/core/util/BaseViewModel.kt
  core/src/main/res/drawable/ic_add.xml
  core/src/main/res/values/dimens.xml
  domain/src/main/java/com/sopt/domain/entity/ConfirmedDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupMembersEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ProgressEntity.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/navigation/GroupNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/ConfirmedDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupMemberViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/navigation/GroupDetailNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/GroupMemberRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ProgressScreen.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/res/drawable/ic_add.xml
  presentation/src/main/res/drawable/ic_group_detail.xml
  presentation/src/main/res/drawable/ic_group_detail_arrow.xml
  presentation/src/main/res/drawable/ic_profile.xml
  presentation/src/main/res/drawable/ic_share.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💟 [UI], :fallen_leaf: 가을

#13 [Feature/#10] : 그룹 홈/그룹 생성 페이지 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/button/NoostakBottomButton.kt
  core/src/main/java/com/sopt/core/designsystem/component/button/NoostakFloatingActionButton.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakCategoryChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakUserChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/snackbar/BaseSnackBar.kt
  core/src/main/java/com/sopt/core/designsystem/component/snackbar/NoostakSnackBar.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/BaseTextField.kt
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/BaseTopAppBar.kt
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/NoostakCloseAppBar.kt
  core/src/main/java/com/sopt/core/designsystem/component/topappbar/NoostakTopAppBar.kt
  core/src/main/java/com/sopt/core/designsystem/screen/NoostakEmptyScreen.kt
  core/src/main/res/drawable/ic_appbar_close.xml
  core/src/main/res/values/dimens.xml
  core/src/main/res/values/strings.xml
  domain/src/main/java/com/sopt/domain/entity/GroupEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupProfileEntity.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/sopt/presentation/example/ExampleRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupFloatingActionButtonItem.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupFloatingActionDialog.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupImage.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupItem.kt
  presentation/src/main/java/com/sopt/presentation/group/navigation/GroupNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/component/GroupProfileImagePicker.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/component/GroupProfileNameTextField.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/navigation/GroupCreateSuccessNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/regex/generateRandomCode.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/navigation/GroupCreateNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/permission/launchImagePicker.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/permission/rememberGalleryLauncher.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/res/drawable/ic_group_create_camera.xml
  presentation/src/main/res/drawable/ic_group_create_delete.xml
  presentation/src/main/res/drawable/ic_group_create_profile.xml
  presentation/src/main/res/drawable/ic_group_fab_close.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💟 [UI], :four_leaf_clover: 언지

#16 [Feature/#15] 공통 컴포넌트 textfield UI 구현
  core/build.gradle.kts
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImagePicker.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  core/src/main/java/com/sopt/core/type/TextFieldType.kt
  core/src/main/java/com/sopt/core/util/permission/ImagePickerLaunchers.kt
  core/src/main/res/drawable/ic_profile.xml
  core/src/main/res/drawable/ic_profile_camera.xml
  core/src/main/res/drawable/ic_text_field_delete.xml
  core/src/main/res/values/strings.xml
  presentation/src/main/java/com/sopt/presentation/group/component/GroupFloatingActionButtonItem.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupFloatingActionDialog.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/component/GroupProfileNameTextField.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: ✅ [MOD], 💟 [UI], :four_leaf_clover: 언지

#19 [Feature/#18] : 타임테이블 수정
  core/src/main/java/com/sopt/core/designsystem/component/timetable/NoostakEditableTimeTable.kt
  core/src/main/java/com/sopt/core/designsystem/component/timetable/NoostakTimeTable.kt
  core/src/main/java/com/sopt/core/util/timetable/TimeTable.kt
  domain/src/main/java/com/sopt/domain/entity/PeriodEntity.kt
  domain/src/main/java/com/sopt/domain/entity/TimeTableEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/CurrentStatusScreen.kt
Labels: ⭐ [FEAT], 🔨 [FIX], :fallen_leaf: 가을

#21 [Feature/#20] : 약속 생성 마지막 2페이지 구현
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakCategoryChip.kt
  core/src/main/java/com/sopt/core/type/CategoryType.kt
  core/src/main/res/values/strings.xml
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmitComplete/AppointmentSubmitCompleteRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmitComplete/AppointmentSubmitCompleteViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/navigation/AppointmentCreateNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/res/drawable/ic_appointment_calendar.xml
  presentation/src/main/res/drawable/ic_appointment_category.xml
  presentation/src/main/res/drawable/ic_appointment_clock.xml
  presentation/src/main/res/values/strings.xml
Labels: ⭐ [FEAT], 💟 [UI], :fallen_leaf: 가을

#24 [Feature/#22] : 그룹 상세, 약속 확정 뷰 엔티티 수정
  core/src/main/java/com/sopt/core/designsystem/component/box/CategoryBox.kt
  core/src/main/java/com/sopt/core/util/CalculateTime.kt
  core/src/main/java/com/sopt/core/util/RearrangeList.kt
  core/src/main/java/com/sopt/core/util/timetable/TimeTable.kt
  domain/src/main/java/com/sopt/domain/entity/AppointmentDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupMembersEntity.kt
  domain/src/main/java/com/sopt/domain/entity/IdentityEntity.kt
  domain/src/main/java/com/sopt/domain/entity/OptionEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ProgressEntity.kt
  domain/src/main/java/com/sopt/domain/entity/RecommendationEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/navigation/GroupDetailNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ProgressScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ♻️ [REFACTOR], :fallen_leaf: 가을

#27 [Feature/#25] 마이페이지 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakCategoryChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/dialog/NoostakDialog.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  core/src/main/java/com/sopt/core/designsystem/theme/Type.kt
  core/src/main/java/com/sopt/core/type/DialogType.kt
  core/src/main/res/values/dimens.xml
  core/src/main/res/values/strings.xml
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/groupMember/GroupMemberRoute.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/component/MyPageItem.kt
  presentation/src/main/java/com/sopt/presentation/mypage/component/MyPageProfileEditButton.kt
  presentation/src/main/java/com/sopt/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/src/main/res/drawable/ic_group_create_success.xml
  presentation/src/main/res/drawable/ic_mypage_arrow.xml
  presentation/src/main/res/values/strings.xml
Labels: 💟 [UI], :four_leaf_clover: 언지

#36 [Hotfix/#35] merge conflict 꼬임 해결
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginFailureDialog.kt
Labels: 🚑️ [HOTFIX], :four_leaf_clover: 언지

#34 [Feature/#26] : 약속 등록 로직 수정 및 바텀네비 수정
  core/src/main/java/com/sopt/core/designsystem/theme/Color.kt
  core/src/main/java/com/sopt/core/designsystem/theme/Type.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmitComplete/AppointmentSubmitCompleteRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/navigation/AppointmentCreateNavigation.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/java/com/sopt/presentation/main/MainTab.kt
  presentation/src/main/res/drawable/ic_appointment_calendar.xml
  presentation/src/main/res/drawable/ic_appointment_category.xml
  presentation/src/main/res/drawable/ic_appointment_clock.xml
  presentation/src/main/res/drawable/ic_appointment_name.xml
  presentation/src/main/res/drawable/ic_appointment_submit_complete.xml
  presentation/src/main/res/drawable/ic_bnv_calendar_off.xml
  presentation/src/main/res/drawable/ic_bnv_calendar_on.xml
  presentation/src/main/res/drawable/ic_bnv_group_off.xml
  presentation/src/main/res/drawable/ic_bnv_group_on.xml
  presentation/src/main/res/drawable/ic_bnv_mypage_off.xml
  presentation/src/main/res/drawable/ic_bnv_mypage_on.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: ➕ [ADD], ✅ [MOD], :fallen_leaf: 가을

#30 [Feature/#29] : 프로필 수정 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImagePicker.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  core/src/main/java/com/sopt/core/type/TextFieldType.kt
  core/src/main/java/com/sopt/core/util/permission/GalleryPermissionHandler.kt
  core/src/main/res/values/strings.xml
  data/src/main/java/com/sopt/data/datasource/UserDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/UserDataSourceImpl.kt
  data/src/main/java/com/sopt/data/repositoryimpl/UserInfoRepositoryImpl.kt
  domain/src/main/java/com/sopt/domain/entity/UserEntity.kt
  domain/src/main/java/com/sopt/domain/repository/UserInfoRepository.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpState.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/navigation/GroupNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/navigation/GroupCreateNavigation.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileState.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: 💟 [UI], :rabbit: 유진

#33 [Feature/#9] : 약속 생성 UI 구현
  core/src/main/java/com/sopt/core/designsystem/component/calendar/NoostakCalendar.kt
  core/src/main/java/com/sopt/core/designsystem/component/checkbox/CircularCheckbox.kt
  core/src/main/java/com/sopt/core/designsystem/component/chip/NoostakCalendarChip.kt
  core/src/main/java/com/sopt/core/designsystem/component/progressbar/NoostakProgressBar.kt
  core/src/main/java/com/sopt/core/designsystem/component/text/NoostakHeaderText.kt
  core/src/main/java/com/sopt/core/designsystem/component/text/NoostakSubHeaderText.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  core/src/main/java/com/sopt/core/designsystem/component/timepicker/NoostakTimePicker.kt
  core/src/main/java/com/sopt/core/designsystem/component/toggle/NoostakSwitch.kt
  core/src/main/res/drawable/ic_calendar_left.xml
  core/src/main/res/drawable/ic_calendar_right.xml
  core/src/main/res/values/dimens.xml
  core/src/main/res/values/strings.xml
  domain/src/main/java/com/sopt/domain/entity/AppointmentCreateEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateInfo/AppointmentCreateInfoRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateInfo/AppointmentCreateInfoViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreatePeriod/AppointmentCreatePeriodRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreatePeriod/AppointmentCreatePeriodViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateTimePicker/AppointmentCreateTimePickerRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateTimePicker/AppointmentCreateTimePickerViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmit/AppointmentSubmitRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentSubmitComplete/AppointmentSubmitCompleteRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/navigation/AppointmentCreateNavigation.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/navigation/CalendarNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/navigation/GroupDetailNavigation.kt
  presentation/src/main/res/drawable/ic_calendar_off.xml
  presentation/src/main/res/drawable/ic_calendar_on.xml
  presentation/src/main/res/drawable/ic_calendar_progress_long.xml
  presentation/src/main/res/drawable/ic_calendar_progress_short.xml
  presentation/src/main/res/drawable/ic_calendar_toggle_off.xml
  presentation/src/main/res/drawable/ic_calendar_toggle_on.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], ✅ [MOD], ♻️ [REFACTOR], 💟 [UI], :cloud: 하늘

#40 [Feature/#38] : 다이얼로그 추가
  core/src/main/java/com/sopt/core/designsystem/component/dialog/AppointmentDialog.kt
  core/src/main/java/com/sopt/core/designsystem/component/dialog/NoostakDialog.kt
  core/src/main/java/com/sopt/core/type/DialogType.kt
  core/src/main/res/values/strings.xml
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LogInRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginFailureDialog.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginViewModel.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/src/main/res/values/strings.xml
Labels: ➕ [ADD], ♻️ [REFACTOR], :fallen_leaf: 가을

#42 [Feature/#37] UI 디테일 수정
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImagePicker.kt
  core/src/main/java/com/sopt/core/designsystem/component/textfield/NoostakTextField.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupFloatingActionDialog.kt
  presentation/src/main/java/com/sopt/presentation/group/navigation/GroupNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/java/com/sopt/presentation/main/MainScreen.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/navigation/MyPageNavigation.kt
  presentation/src/main/res/drawable/ic_group_fab_create.xml
  presentation/src/main/res/drawable/ic_group_fab_enter.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], 💟 [UI], :four_leaf_clover: 언지
