Repository Noostak/Noostak_Android, pull requests merged in 2025-03, with the labels that each got.

#60 [Feature/#59] 그룹 홈/상세, 마이페이지 API entity 맞추기
  domain/src/main/java/com/sopt/domain/entity/GroupEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ProfileEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleDetailScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupItem.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
Labels: 🛠️ [CHORE], ✅ [MOD], :four_leaf_clover: 언지

#57 [Feature/#54] : 로그인, 회원가입 API 연결
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/Qualifier.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/RetrofitModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  app/src/main/java/com/sopt/noostak/di/TokenInterceptor.kt
  app/src/main/java/com/sopt/noostak/di/UserInfoModule.kt
  core/src/main/java/com/sopt/core/type/SocialType.kt
  data/src/main/java/com/sopt/data/datasource/AccountDataSource.kt
  data/src/main/java/com/sopt/data/datasource/AuthDataSource.kt
  data/src/main/java/com/sopt/data/datasource/UserDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/AccountDataSourceImpl.kt
  data/src/main/java/com/sopt/data/datasourceimpl/AuthDataSourceImpl.kt
  data/src/main/java/com/sopt/data/datasourceimpl/UserDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/request/RequestPostSocialLoginDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponsePostReissueTokenDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponsePostSignUpDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponsePostSocialLoginDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponsePostSignUpDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponsePostSocialLoginDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/AccountRepositoryImpl.kt
  data/src/main/java/com/sopt/data/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/sopt/data/repositoryimpl/UserInfoRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/AccountApiService.kt
  data/src/main/java/com/sopt/data/service/ApiKeyStorage.kt
  data/src/main/java/com/sopt/data/service/AuthApiService.kt
  domain/src/main/java/com/sopt/domain/entity/AuthEntity.kt
  domain/src/main/java/com/sopt/domain/repository/AccountRepository.kt
  domain/src/main/java/com/sopt/domain/repository/AuthRepository.kt
  domain/src/main/java/com/sopt/domain/repository/UserInfoRepository.kt
  domain/src/main/java/com/sopt/domain/usecase/DeleteWithdrawUseCase.kt
  domain/src/main/java/com/sopt/domain/usecase/PostLogoutUseCase.kt
  domain/src/main/java/com/sopt/domain/usecase/PostSignUpUseCase.kt
  domain/src/main/java/com/sopt/domain/usecase/PostSocialLoginUseCase.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LogInRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/OnboardingRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/navigation/LoginNavigation.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/navigation/SignUpNavigation.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
Labels: ⭐ [FEAT], :rabbit: 유진

#67 [Fix/#62] 1차 스프린트 QA 반영
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  core/src/main/java/com/sopt/core/designsystem/component/button/NoostakFloatingActionButton.kt
  core/src/main/java/com/sopt/core/designsystem/component/dialog/NoostakDialog.kt
  core/src/main/java/com/sopt/core/designsystem/component/image/ProfileImagePicker.kt
  core/src/main/java/com/sopt/core/designsystem/screen/NoostakLoadingScreen.kt
  core/src/main/java/com/sopt/core/type/DialogType.kt
  core/src/main/java/com/sopt/core/type/ImagePickerType.kt
  core/src/main/res/drawable/ic_fab_add.xml
  core/src/main/res/drawable/ic_group_profile.xml
  core/src/main/res/drawable/ic_profile.xml
  core/src/main/res/drawable/ic_profile_camera.xml
  core/src/main/res/drawable/ic_user_profile.xml
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LogInRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleDetailScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleDetailTopAppBar.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/navigation/CalendarNavigation.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupImage.kt
  presentation/src/main/java/com/sopt/presentation/group/component/GroupItem.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/component/GroupCreateSuccessCopyButton.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/regex/GenerateRandomCode.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileRoute.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/mypage/editProfile/EditProfileViewModel.kt
  presentation/src/main/res/drawable/ic_group_create_success.xml
  presentation/src/main/res/drawable/ic_group_profile.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔨 [FIX], ✅ [MOD], 💟 [UI], :four_leaf_clover: 언지

#64 [Feature/#63] : 1차 QA 반영
  core/src/main/java/com/sopt/core/type/ProfileType.kt
  core/src/main/res/drawable/ic_group_image.xml
  core/src/main/res/drawable/ic_profile_image.xml
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/SignUpViewModel.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/checkInvite/CheckInviteRoute.kt
  presentation/src/main/java/com/sopt/presentation/auth/signup/inputGroupCode/InputGroupCodeRoute.kt
  presentation/src/main/res/drawable/ic_invite_code.xml
  presentation/src/main/res/values/strings.xml
Labels: ✅ [MOD], 💟 [UI], :rabbit: 유진

#71 [Feature/#68] 그룹 홈/생성 API 연결
  app/src/main/java/com/sopt/noostak/di/ContentResolverModule.kt
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  data/src/main/java/com/sopt/data/datasource/GroupDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/GroupDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetGroupsDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponsePostGroupDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponsePostGroupDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/GroupRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/GroupApiService.kt
  data/src/main/java/com/sopt/data/util/ContentUriRequestBody.kt
  data/src/main/java/com/sopt/data/util/CreateImagePart.kt
  data/src/main/java/com/sopt/data/util/GetErrorMessage.kt
  domain/src/main/java/com/sopt/domain/entity/GroupEntity.kt
  domain/src/main/java/com/sopt/domain/entity/GroupSuccessEntity.kt
  domain/src/main/java/com/sopt/domain/entity/network/Error.kt
  domain/src/main/java/com/sopt/domain/repository/GroupRepository.kt
  presentation/src/main/java/com/sopt/presentation/auth/login/LoginViewModel.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupRoute.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/group/GroupViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/GroupCreateSuccessRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/navigation/GroupCreateSuccessNavigation.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/groupCreateSuccess/regex/Regex.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/navigation/GroupCreateNavigation.kt
Labels: ⭐ [FEAT], :four_leaf_clover: 언지

#70 [Feature/#58] : 캘린더 약속 정보 가져오기 API 연결
  app/src/main/java/com/sopt/noostak/di/DataSourceModule.kt
  app/src/main/java/com/sopt/noostak/di/RepositoryModule.kt
  app/src/main/java/com/sopt/noostak/di/ServiceModule.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonth.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarMonthPager.kt
  core/src/main/java/com/sopt/core/designsystem/component/calendar/CalendarWeek.kt
  core/src/main/java/com/sopt/core/extension/CalendarExt.kt
  core/src/main/java/com/sopt/core/util/calendar/FormattedKoreanDate.kt
  data/src/main/java/com/sopt/data/datasource/CalendarDataSource.kt
  data/src/main/java/com/sopt/data/datasourceimpl/CalendarDataSourceImpl.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetCalendarDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetCalendarDtoMapper.kt
  data/src/main/java/com/sopt/data/repositoryimpl/CalendarRepositoryImpl.kt
  data/src/main/java/com/sopt/data/service/ApiKeyStorage.kt
  data/src/main/java/com/sopt/data/service/CalendarApiService.kt
  domain/src/main/java/com/sopt/domain/entity/CalendarEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  domain/src/main/java/com/sopt/domain/repository/CalendarRepository.kt
  domain/src/main/java/com/sopt/domain/usecase/GetCalendarAppointmentsUseCase.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarMonthScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
Labels: ⭐ [FEAT], :rabbit: 유진

#73 [Feature/#69] : 그룹 약속 엠티뷰 & 옵션 클릭 시 색상 변경
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/GroupDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ProgressScreen.kt
  presentation/src/main/res/drawable/ic_group_detail_empty.xml
Labels: ✅ [MOD], 💟 [UI], :fallen_leaf: 가을
